
name: Sync Discussion
on: discussion
jobs: 
  SyncDiscussion: 
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps: 
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Use PSJekyll Action
        uses: PowerShellWeb/PSJekyll@main
        id: PSJekyll
        with: 
          TargetBranch: edits-$([DateTime]::Now.ToString("o") -replace "T.+$")
          CommitMessage: Syncing Discussions [skip ci]

